package com.example.android.mediumtest.model

object Countries {
    private var allCountry = arrayListOf(
        Country(false,"Argentina", "ar"),
        Country(false,"Australia", "au"),
        Country(false,"Austria", "at"),
        Country(false,"Belgium", "be"),
        Country(false,"Brazil", "br"),
        Country(false,"Bulgaria", "bg"),
        Country(false,"Canada", "ca"),
        Country(false,"China", "cn"),
        Country(false,"Colombia", "co"),
        Country(false,"Cuba", "cu"),
        Country(false,"Czech Republic", "cz"),
        Country(false,"Egypt", "eg"),
        Country(false,"France", "fr"),
        Country(false,"Germany", "de"),
        Country(false,"Greece", "gr"),
        Country(false,"Hong Kong", "hk"),
        Country(false,"Hungary", "hu"),
        Country(false,"India", "in"),
        Country(false,"Indonesia", "id"),
        Country(false,"Ireland", "ie"),
        Country(false,"Israel", "il"),
        Country(false,"Italy", "it"),
        Country(false,"Japan", "jp"),
        Country(false,"Latvia", "lv"),
        Country(false,"Lithuania", "lt"),
        Country(false,"Malaysia", "my"),
        Country(false,"Mexico", "mx"),
        Country(false,"Morocco","ma"),
        Country(false,"Netherlands", "nl"),
        Country(false,"New Zealand", "nz"),
        Country(false,"Nigeria", "ng"),
        Country(false,"Norway", "no"),
        Country(false,"Philippines", "ph"),
        Country(false,"Poland", "pl"),
        Country(false,"Portugal", "pt"),
        Country(false,"Romania", "ro"),
        Country(false,"Russia", "ru"),
        Country(false,"Saudi Arabia", "sa"),
        Country(false,"Serbia", "rs"),
        Country(false,"Singapore", "sg"),
        Country(false,"Slovakia", "sk"),
        Country(false,"Slovenia", "si"),
        Country(false,"South Africa", "za"),
        Country(false,"South Korea", "kr"),
        Country(false,"Sweden", "se"),
        Country(false,"Switzerland", "ch"),
        Country(false,"Taiwan", "tw"),
        Country(false,"Thailand", "th"),
        Country(false,"Turkey", "tr"),
        Country(false,"UAE", "ae"),
        Country(false,"Ukraine", "ua"),
        Country(false,"United Kingdom", "gd"),
        Country(false,"United State", "us"),
        Country(false,"Venuzuela", "ve")
    )

    fun getAllCountries() = allCountry
}